version: '3.9'
services:
  redis-db:
    image: redis:7-alpine
    command: --requirepass ${REDIS_PASSWORD}
    ports:
      - 16379:6379
  faucet:
    build:
      context: ./
      dockerfile: ./Dockerfile
    environment:
      WALLET_PRIVATE_KEY: ${WALLET_PRIVATE_KEY}
      ENABLE_TRANSACTION_CHECKS: ${ENABLE_TRANSACTION_CHECKS}
      ETHERSCAN_API_KEY: ${ETHERSCAN_API_KEY}
      REDIS_URL: ${REDIS_URL}
      RECAPTCHA_SECRET_KEY: ${RECAPTCHA_SECRET_KEY}
      TWITTEER_BEARER_TOKEN: ${TWITTEER_BEARER_TOKEN}
      TWITTER_CONSUMER_KEY: ${TWITTER_CONSUMER_KEY}
      TWITTER_CONSUMER_SECRET: ${TWITTER_CONSUMER_SECRET}
      SESSION_SECRET: ${SESSION_SECRET}
      TWITTER_CLIENT_ID: ${TWITTER_CLIENT_ID}
      TWITTER_CLIENT_SECRET: ${TWITTER_CLIENT_SECRET}
      NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}
      NEXTAUTH_URL: ${NEXTAUTH_URL}
    ports:
      - 3000:3000
  gateway:
    image: nginx:1.25-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - '80:80'
