version: '3.9'
services:
  redis-db:
    image: redis:7-alpine
    command: --requirepass ${REDIS_PASSWORD}
    ports:
      - 16379:6379
  faucet:
    build:
      context: ./
      dockerfile: ./Dockerfile
      args:
        NEXT_PUBLIC_WALLET_ADDRESS: ${NEXT_PUBLIC_WALLET_ADDRESS}
        NEXT_PUBLIC_DEFAULT_WALLET_ETH_AMOUNT: ${NEXT_PUBLIC_DEFAULT_WALLET_ETH_AMOUNT}
        NEXT_PUBLIC_PRIVILEGED_WALLET_ETH_AMOUNT: ${NEXT_PUBLIC_PRIVILEGED_WALLET_ETH_AMOUNT}
        NEXT_PUBLIC_DEFAULT_WALLET_BNB_AMOUNT: ${NEXT_PUBLIC_DEFAULT_WALLET_BNB_AMOUNT}
        NEXT_PUBLIC_ENABLE_CAPTCHA: ${NEXT_PUBLIC_ENABLE_CAPTCHA}
        NEXT_PUBLIC_RECAPTCHA_SITE_KEY: ${NEXT_PUBLIC_RECAPTCHA_SITE_KEY}
        NEXT_PUBLIC_ALCHEMY_SEPOLIA_RPC: ${NEXT_PUBLIC_ALCHEMY_SEPOLIA_RPC}
        NEXT_PUBLIC_ALCHEMY_GOERLI_RPC: ${NEXT_PUBLIC_ALCHEMY_GOERLI_RPC}
        NEXT_PUBLIC_MUMBAI_RPC: ${NEXT_PUBLIC_MUMBAI_RPC}
        NEXT_PUBLIC_BASE_RPC: ${NEXT_PUBLIC_BASE_RPC}
        NEXT_PUBLIC_ARBITRUM_GOERLI_RPC: ${NEXT_PUBLIC_ARBITRUM_GOERLI_RPC}
        NEXT_PUBLIC_BNB_RPC: ${NEXT_PUBLIC_BNB_RPC}
        NEXT_PUBLIC_OPTIMISM_RPC: ${NEXT_PUBLIC_OPTIMISM_RPC}
    environment:
      WALLET_PRIVATE_KEY: ${WALLET_PRIVATE_KEY}
      ENABLE_TRANSACTION_CHECKS: ${ENABLE_TRANSACTION_CHECKS}
      ETHERSCAN_API_KEY: ${ETHERSCAN_API_KEY}
      REDIS_URL: ${REDIS_URL}
      RECAPTCHA_SECRET_KEY: ${RECAPTCHA_SECRET_KEY}
      TWITTEER_BEARER_TOKEN: ${TWITTEER_BEARER_TOKEN}
      TWITTER_CONSUMER_KEY: ${TWITTER_CONSUMER_KEY}
      TWITTER_CONSUMER_SECRET: ${TWITTER_CONSUMER_SECRET}
      SESSION_SECRET: ${SESSION_SECRET}
      TWITTER_CLIENT_ID: ${TWITTER_CLIENT_ID}
      TWITTER_CLIENT_SECRET: ${TWITTER_CLIENT_SECRET}
      NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}
      NEXTAUTH_URL: ${NEXTAUTH_URL}
    ports:
      - 3000:3000
