version: "3.9"
services:
  faucet:
    build:
      context: ./
      dockerfile: ./Dockerfile
      args:
        NEXT_PUBLIC_WALLET_ADDRESS: ${NEXT_PUBLIC_WALLET_ADDRESS}
        NEXT_PUBLIC_ALCHEMY_SEPOLIA: ${NEXT_PUBLIC_ALCHEMY_SEPOLIA}
        NEXT_PUBLIC_DEFAULT_WALLET_ETH_AMOUNT: ${NEXT_PUBLIC_DEFAULT_WALLET_ETH_AMOUNT}
        NEXT_PUBLIC_PRIVILEGED_WALLET_ETH_AMOUNT: ${NEXT_PUBLIC_PRIVILEGED_WALLET_ETH_AMOUNT}
        NEXT_PUBLIC_ENABLE_CAPTCHA: ${NEXT_PUBLIC_ENABLE_CAPTCHA}
        NEXT_PUBLIC_RECAPTCHA_SITE_KEY: ${NEXT_PUBLIC_RECAPTCHA_SITE_KEY}
    env_file: .env
    ports:
      - 3000:3000
