name: Migrate database

on:
  push:
    branches:
      - main
    paths:
      - prisma/**

  workflow_dispatch:
    inputs:
      hubAddressGroupObject:
        type: choice
        description: 'Deploy service 🚀🚀🚀'
        required: true
        default: 'deploy'
        options:
          - 'deploy'

    branches:
      - main

env:
  VAULT_SERVER: https://vault.caliber.build

jobs:
  build-prod:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Pre-check step and set env dev
        id: get_current_env_prod
        if: ${{ github.event.ref == 'refs/heads/main' }}
        run: |
          if [[ ${{ github.event.ref }} == 'refs/heads/main' ]]; then
            echo "CURRENT_ENV=prod" >> "$GITHUB_ENV"
            echo "[INFO] PASSED pre-check. Using build automatically"
            echo "[INFO] PASSED pre-check. Using build automatically"
            exit 0
          else
            echo "[ERR] You are not allowed to run pipeline"
            echo "[ERR] Your action has been reported to your admin"
            exit 1
          fi

      - name: Import Secrets
        id: import-secrets
        uses: hashicorp/vault-action@v2
        with:
          url: ${{ env.VAULT_SERVER }}
          token: ${{ secrets.VAULT_TOKEN }}
          tlsSkipVerify: true
          secrets: |
            /kv-v2/data/sre-data/github PRITUNL_PROFILE_FILE | PRITUNL_PROFILE_FILE;
            /kv-v2/data/faucet/prod DATABASE_URL | DATABASE_URL;

      - name: Setup Pritunl Profile and Start VPN Connection
        uses: nathanielvarona/pritunl-client-github-action@v1
        with:
          profile-file: ${{ env.PRITUNL_PROFILE_FILE }}

      - name: Migrate database
        shell: bash
        timeout-minutes: 15 #####
        run: |
          rm .yarnrc.yml
          cp -r prisma ./migrator
          cd migrator
          yarn install
          yarn migrate

